spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/notesdb0
    username: usr
    password: pwd
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    database: default
    generate-ddl: false
    hibernate:
      ddl-auto: none

    show-sql: true
    properties:
      hibernate:
    #format_sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration/postgres

logging:
  level:
    ROOT: ERROR
    org.hibernate.engine.transaction.internal: DEBUG